plugins {
	id 'fabric-loom'
}

apply from: "versions.gradle"

def mc_version_name(){
	String key = 'minecraft_version_name'
	if (project.hasProperty(key)) {String value = project.getProperties().get(key); return !value.isEmpty() ? value : project.minecraft_version}
	else {return project.minecraft_version}
}
version = "${mod_version}+${mc_version_name()}-Fabric"

base {
	archivesName = project.archives_base_name
}

repositories {
	maven {
		name = 'ParchmentMC'
		url = 'https://maven.parchmentmc.org'
	}
	maven {
		name = 'Modrinth'
		url = 'https://api.modrinth.com/maven'
	}
}

loom {
	splitEnvironmentSourceSets()

	mods {
		"more_nemos_woodcutter_variants" {
			sourceSet sourceSets.main
			sourceSet sourceSets.client
		}
	}

	log4jConfigs.from(file("log4j.xml"))
}

def releaseVersion = getReleaseVersion(minecraft_version)
def (fabric_loader_version, fabric_loader_version_0, fabric_api_version) = latestFabric(releaseVersion)
def (pMinecraftVersion, mostRecentParchmentDate) = latestParchment(releaseVersion)

dependencies {
	implementation 'org.apache.commons:commons-text:1.12.0'
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	mappings loom.layered() {
		officialMojangMappings()
		parchment("org.parchmentmc.data:parchment-${pMinecraftVersion}:${mostRecentParchmentDate}@zip")
	}
	modImplementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
	modImplementation "net.fabricmc.fabric-api:fabric-api:${fabric_api_version}"

	// Nemoʼs Woodcutter
	modCompileOnly modRuntimeOnly("maven.modrinth:nemos-woodcutter:${project.nemos_woodcutter_version_id}")
}

def minecraft_version_0 = lowerMinecraftVersion(minecraft_version_lower)
def minecraft_version_1 = upperMinecraftVersion(minecraft_version_upper)
def (java_version, java_version_enum) = javaVersions(releaseVersion)

def replaceProperties = [
		mod_id: mod_id, mod_name: mod_name, mod_description: mod_description, mod_license: mod_license,
		mod_version: mod_version,  nemos_woodcutter_version: nemos_woodcutter_version,
		min_floader_version: fabric_loader_version_0,
		minecraft_version_0: minecraft_version_0, minecraft_version_1: minecraft_version_1, java_version: java_version
]
println "===\nExpanding the following values into fabric.mod.json and *.mixins.json:\n${replaceProperties.collect { k, v -> "  ${k}: ${v}" }.join('\n')}\n==="

["processResources", "processClientResources"].each { taskName ->
	tasks.named(taskName) {
		inputs.properties replaceProperties

		filesMatching("fabric.mod.json") {
			expand replaceProperties
		}
		filesMatching("*.mixins.json") {
			expand replaceProperties
		}
	}
}


tasks.withType(JavaCompile).configureEach {
	it.options.release = java_version
}

java {
	sourceCompatibility = java_version_enum
	targetCompatibility = java_version_enum
}

jar {
	from("LICENSE") {
		rename { "${it}_${project.base.archivesName.get()}"}
	}
}