# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
minecraft_version=1.21.1
loader_version=0.16.10
fapi_version=0.115.3+1.21.1

# Mod Properties
mod_id=morenemoswoodcuttervariants
mod_name=More Nemo's Woodcutter Variants
mod_description=The Woodcutter Variants are just like the Woodcutter. Just made out of different wood!
mod_license=MIT
mod_version=1.1.4
maven_group=de.pnku
archives_base_name=MoreNemosWoodcutterVariants

# Dependencies
nemos_woodcutter_version=XDslDeud