# Done to increase the memory available to gradle.
org.gradle.jvmargs = -Xmx4G
org.gradle.parallel = true

# Minecraft Properties
minecraft_version = 1.21.11
minecraft_version_supported = [1.21.4,1.21.11]
game_version_filter = releases
minecraft_version_lower = 1.21.3
minecraft_version_upper = 1.22.0

# File Name
minecraft_version_name = 1.21.4(-11)
archives_base_name=MoreNemosWoodcutterVariants

# Mod Properties
mod_id=more_nemos_woodcutter_variants
mod_name=More Nemo's Woodcutter Variants
mod_name_short=More Nemo's Woodcutter Variants
mod_description=The Woodcutter Variants are just like the Woodcutter. Just made out of different wood!
mod_license=MIT
mod_version=2.1.1
maven_group=de.pnku

# Dependencies [!]
nemos_woodcutter_version=1.21.11-1.14.1
nemos_woodcutter_version_id=q7Myyhad